# Generated by Django 3.0.3 on 2020-04-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=10)),
                ('jyutping', models.CharField(max_length=20)),
                ('english', models.CharField(max_length=20)),
                ('audio', models.FileField(upload_to='.')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_word', to='vocabulary.Word')),
                ('opt1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt1', to='vocabulary.Word')),
                ('opt2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt2', to='vocabulary.Word')),
                ('opt3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt3', to='vocabulary.Word')),
                ('opt4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt4', to='vocabulary.Word')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_word', to='vocabulary.Word')),
            ],
        ),
    ]
